version: '3.9'

services:
  pokemon-service:
    build: ./pokemon-service/src
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      - DB_URL=mongodb://db/pokemon
      - SECRET_KEY=your-secret-key

    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - t1-volume:/data/db


volumes:
    t1-volume: